// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using IzolluVakfi.Data;

#nullable disable

namespace IzolluVakfi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260520000002_AddErrorLogs")]
    partial class AddErrorLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
